apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels: nginx-test
spec:

  restartPolicy: Never
  select : nginx-test

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80

  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/bash"]