apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels: 
    name : nginx-test
spec:

  restartPolicy: Always

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80

  - name: install
    image: busybox
    
    command: ["/bin/bash"]