apiVersion: v1
kind: Service
metadata:
  name: two-containers
  labels:
   name: two-containers
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
    nodePort: 30088
  selector:
    name: two-containers